/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;
import ClassesInterfaces.DatabaseWorks;
import java.sql.*;
import javax.swing.*;
import ClassesInterfaces.*;

/**
 *
 * @author Halil
 */
public class creditCardToBankWindow extends javax.swing.JPanel {
    private long creditCardId;
    private long amount;
    private JFrame frame;
    User programUser;

    /**
     * Creates new form creditCardToBankWindow
     */
    public creditCardToBankWindow(User programUser, JFrame frame) {
        initComponents();
        this.programUser = programUser;
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        creditCardIdField = new javax.swing.JTextField();
        amountField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Lutfen kredi karti IDsini ve aktarmak istediginiz para miktarini giriniz");

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("Kredi Karti ID");

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setText("Para Miktari");

        jButton1.setText("Aktar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(creditCardIdField)
                                        .addComponent(amountField))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditCardIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String creditCardIdS = this.creditCardIdField.getText();
        String amountS = this.amountField.getText();
        String query = null;
        JFrame f = null;
        

        
        if(creditCardIdS.equals("") || amountS.equals("")){
            f = new JFrame();
            JOptionPane.showMessageDialog(f, 
                    "Lutfen  kredi karti ID ve miktar kisimlarini bos birak"
                            + "mayiniz");
        }
        
        else if(Long.valueOf(amountS) < 0){
            f = new JFrame();
            JOptionPane.showMessageDialog(f, 
                    "Lutfen miktar kismini negatif girmeyiniz");
        }
        else if(!DatabaseWorks.contains(Long.valueOf(creditCardIdS))){
            f = new JFrame();
            JOptionPane.showMessageDialog(f,
                    "Boyle bir kredi karti ID yok lutfen var olan bir kredi"
                            + "karti ID giriniz");
        }
        else if(DatabaseWorks.larger(Long.valueOf(creditCardIdS), 
                Long.valueOf(amountS))){
            f = new JFrame();
            JOptionPane.showMessageDialog(f,
                    "Aktarmak istediginiz para miktari kredi kartinizda kalan"
                            + " harcayabiliceginiz paradan fazla lutfen"
                            + "kabul edilebilir bir miktar giriniz"); 
        }
        
        else{
            
              
            this.amount = Long.valueOf(amountS);
            this.creditCardId = Long.valueOf(creditCardIdS);
            
        query = "UPDATE CreditCard\n"
                + "SET RemainingAmount = (SELECT RemainingAmount FROM CreditCard\n"
                + "WHERE CreditCardID = " + creditCardId + ") - " + amount
                + "\nWHERE CreditCardID = " + creditCardId + ";";
        
        try (Connection conn = DriverManager.getConnection(DatabaseUrl.URL);
                Statement stat = conn.createStatement()) {
            stat.execute(query);

        } catch (SQLException exp) {
            JFrame j = new JFrame();
            JOptionPane.showMessageDialog(j, exp.toString());

        }

        query = "UPDATE BankAccounts\n"
                + "SET BankBalance = "
                + amount + " + (SELECT BankBalance FROM BankAccounts WHERE ID = " + this.programUser.getId() + ")"
                + "\nWHERE ID = " + this.programUser.getId() + ";";

        try (Connection conn = DriverManager.getConnection(DatabaseUrl.URL);
                Statement stat = conn.createStatement()) {
                stat.execute(query);
                Engine.refresh();
                frame.dispose();

        } catch (SQLException exp) {
            JFrame j = new JFrame();
            JOptionPane.showMessageDialog(j, exp.toString());
        }
        
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JTextField creditCardIdField;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
