/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import javax.swing.*;
import java.sql.*;
import ClassesInterfaces.*;

/**
 *
 * @author Halil
 */
public class LimitChangeDemands extends javax.swing.JPanel {
    private JFrame parent;

    /**
     * Creates new form limitChangeDemands
     */
    public LimitChangeDemands(JFrame parent) {
        initComponents();
        this.parent = parent;
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        Accept = new javax.swing.JButton();
        IdTextField = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        Deny = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Limit Degisim Talepleri");

        Accept.setText("Kabul Et");
        Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setText("Istek ID:");

        Deny.setText("Reddet");
        Deny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DenyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IdTextField))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(Accept)
                        .addGap(30, 30, 30)
                        .addComponent(Deny)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Accept)
                    .addComponent(Deny))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptActionPerformed
        // TODO add your handling code here:
        String demandID = this.IdTextField.getText();
        int confirmation = 0;
        long creditCardId = 0;
        long amount = 0;
        JFrame f = null;
        if (demandID.equals("")) {
            f = new JFrame();
            JOptionPane.showMessageDialog(f, ""
                    + "Lutfen istek IDsi kismini bos birakmayiniz");
        } else {
            
            String query = "SELECT EXISTS(SELECT 1 FROM LimitIncreaseDemands\n"
                    + "WHERE DemandID = " + demandID + ")";

            try (Connection conn = DriverManager.getConnection(DatabaseUrl.URL);
                    Statement stat = conn.createStatement();
                    ResultSet result = stat.executeQuery(query)) {
                confirmation = result.getInt(1);
            } catch (SQLException exp) {
                f = new JFrame();
                JOptionPane.showMessageDialog(f, exp.toString());
            }

            if (confirmation == 1) {
                query = "SELECT CreditCardId, Amount FROM "
                        + "LimitIncreaseDemands\n"
                        + "WHERE DemandID = " + demandID;
                try (Connection conn = DriverManager.getConnection
                        (DatabaseUrl.URL);
                        Statement stat = conn.createStatement()) 
                    {

                        try (ResultSet result = stat.executeQuery(query)) {
                            creditCardId = result.getLong(1);
                            amount = result.getLong(2);
                        }
                        
                        query = "UPDATE CreditCard SET CreditCardAmount = "
                                + amount + " WHERE CreditCardId = " + 
                                creditCardId;
                        
                        stat.execute(query);
                        
                        query = "DELETE FROM LimitIncreaseDemands\n"
                                + "WHERE DemandID = " + demandID;
                        
                        stat.execute(query);
                        Engine.refresh();
                        this.parent.dispose();

                } catch (SQLException exp) {
                    f = new JFrame();
                    JOptionPane.showMessageDialog(f, exp.toString());
                }
            }
            else{
                f = new JFrame();
                    JOptionPane.showMessageDialog(f,
                            "Lutfen var olan bir istek Idsi giriniz");
            }
        }
    }//GEN-LAST:event_AcceptActionPerformed

    private void DenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DenyActionPerformed
        // TODO add your handling code here:
        String demandId = this.IdTextField.getText();
        JFrame f = null;
        int confirmation = 0;
        
        if(demandId.equals("")){
            f = new JFrame();
            JOptionPane.showMessageDialog(f, 
                    "Lutfen Istek IDsi kismini bos birakmayiniz");
        }
        else{
             
            String query = "SELECT EXISTS(SELECT 1 FROM LimitIncreaseDemands\n"
                    + "WHERE DemandID = " + demandId + " )";

            try (Connection conn = DriverManager.getConnection(DatabaseUrl.URL);
                    Statement stat = conn.createStatement();
                    ResultSet result = stat.executeQuery(query)) {
                confirmation = result.getInt(1);
            } catch (SQLException exp) {
                f = new JFrame();
                JOptionPane.showMessageDialog(f, exp.toString());
            }
             query = "DELETE FROM LimitIncreaseDemands\n"
                                + "WHERE DemandID = " + demandId;
            
            if(confirmation == 1){
                try(Connection conn = DriverManager.getConnection(DatabaseUrl.URL);
                        Statement stat = conn.createStatement()
                        ){
                    stat.execute(query);
                    this.parent.dispose();
                }
                catch(SQLException exp){
                    f = new JFrame();
                    JOptionPane.showMessageDialog(f, exp.toString());
                }
            }
        }
    }//GEN-LAST:event_DenyActionPerformed

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accept;
    private javax.swing.JButton Deny;
    private javax.swing.JTextField IdTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
