/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import ClassesInterfaces.DatabaseWorks;
import java.sql.*;
import javax.swing.*;
import ClassesInterfaces.*;
import java.awt.event.*;



/**
 *
 * @author Halil
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private static Login core;
    private static JPanel sameWindow;

    public static JPanel getSameWindow() {
        return sameWindow;
    }

    public static void setSameWindow(JPanel sameWindow) {
        Login.sameWindow = sameWindow;
    }

   

    public Login() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(356, 466);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JPasswordField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        register = new javax.swing.JButton();
        enter = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setText("Kullanici Adi");

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(204, 204, 204));
        jTextField4.setText("Sifre");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Giris Yapiniz \nHesabiniz Yoksa Kaydolunuz\n");
        jScrollPane1.setViewportView(jTextArea1);

        register.setText("Kaydol");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        enter.setText("Giris Yap");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Bu program SQLite kullanmaktadir.\nVeritabani icerigine DB Browser For SQLite\nprogrami uzerinden bakilabilir.\n");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField3)
                                .addComponent(jTextField4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(passwordInput, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                .addComponent(usernameInput)))
                        .addComponent(enter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(enter)
                .addGap(18, 18, 18)
                .addComponent(register)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // TODO add your handling code here:
        String answer = null;
        String username = this.usernameInput.getText();
        String password = this.passwordInput.getText();
        boolean confirmation = false;
        JFrame f = null;
        if(username.equals("") ||  password.equals("")){
            f = new JFrame();
            JOptionPane.showMessageDialog(f, "Lutfen kullanici adi veya sifre"
                    + " kismini bos birakmayiniz");
            return;
        }
        
        String query = "SELECT EXISTS(SELECT 1 FROM ProgramAccounts\n"
                + "WHERE Username = " + "'" + username + "'"
                + " AND Password = " + "'" + password + "'"
                + ");";
             
        
        try (Connection conn = DriverManager.getConnection(DatabaseUrl.URL);
                Statement stat = conn.createStatement()) {
            try(ResultSet result = stat.executeQuery(query)){
                confirmation = result.getBoolean(1);
            }
            
            if(confirmation == true){
                query = "SELECT ProgramAccounts.ID, BankAccounts.IBAN ,"
                + "BankAccounts.BankBalance,SUM(Bills.BillAmount)"
                 + "AS SumOfBills, ProgramAccounts.Type\n" 
                +  "FROM ProgramAccounts\n" 
                +  "LEFT JOIN BankAccounts\n" 
                +  "ON ProgramAccounts.ID = BankAccounts.ID\n" 
                +  "LEFT JOIN Bills\n"                 
                +  "ON ProgramAccounts.ID = Bills.ID\n" 
                  + "WHERE ProgramAccounts.Username = "
                +  "'" + username + "'" 
                +  "AND Password =" + "'" + password + "'" + ";";
                

                
                try(ResultSet result = stat.executeQuery(query)){
                    String type = result.getString(5);
                    if(type.equals("Musteri")){
                        
                        f = new JFrame();
                        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        CustomerWindow window = new CustomerWindow
                        (result.getLong(1), result.getLong(2),
                        result.getLong(3), result.getLong(4), username,
                        password, this, f);
                        sameWindow = window;
                        Engine.refresh();
                        f.add(window);
                        f.setSize(811, 600);
                        f.setLocationRelativeTo(null);
                        this.setVisible(false);
                        f.setVisible(true);
                    }
                    else if(type.equals("Calisan")){
                        f = new JFrame();
                        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        EmployeeWindow window = new EmployeeWindow
                        (result.getLong(1), result.getLong(2),
                        result.getLong(3), result.getLong(4), username,
                        password, this, f);
                        sameWindow = window;
                        Engine.refresh();
                        f.add(window);
                        f.setSize(1438, 750);
                        f.setLocationRelativeTo(null);
                        this.setVisible(false);
                        f.setVisible(true);
                    }
                    else if(type.equals("Yonetici")){
                        f = new JFrame();
                        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        ManagerWindow window = new ManagerWindow(result.getLong(1), result.getLong(2),
                        result.getLong(3), result.getLong(4), username,
                        password, this, f);
                        sameWindow = window;
                        Engine.refresh();
                        f.add(window);
                        f.setSize(790, 650);
                        f.setLocationRelativeTo(null);
                        this.setVisible(false);
                        f.setVisible(true);
                    }
                }
            }
            else{
                JOptionPane.showMessageDialog(new JFrame(), "Kullanici adi veya"
                        + " sifreyi yanlis girdiniz");
            }
        } catch (SQLException exp) {
            f = new JFrame();
            JOptionPane.showMessageDialog(f, exp.toString());
        }
    }//GEN-LAST:event_enterActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        JFrame f = new JFrame();
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
        RegisterWindow window = new RegisterWindow(this, f);
        String username = null;
        String password = null;
        String query = null;
        f.add(window);
        f.setSize(367, 320);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login.core = new Login();
                Login.core.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JButton register;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
