/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import ClassesInterfaces.DatabaseWorks;
import java.sql.*;
import javax.swing.*;
import ClassesInterfaces.*;

/**
 *
 * @author Halil
 */
public class ObjectBillWindow extends javax.swing.JPanel {

    private String billId;
    private User programUser;
    private JFrame parent;

    public JTable getObjectBillTable() {
        return objectBillTable;
    }

    public void setObjectBillTable(JTable objectBillTable) {
        this.objectBillTable = objectBillTable;
    }
    
    

    public String getBillId() {
        return billId;
    }

    public void setBillId(String billId) {
        this.billId = billId;
    }

    /**
     * Creates new form objectBillWindow
     */
    public ObjectBillWindow(User programUser, JFrame parent) {
        initComponents();
        this.programUser = programUser;
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        billIdTextField = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        objectBillTable = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        sendBillObjectButton = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jTextField3.setText("jTextField3");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(204, 204, 204));
        jTextField4.setText("Lutfen itiraz gondermek istedigniz faturanin ID sini giriniz");

        objectBillTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(objectBillTable);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(204, 204, 204));
        jTextField5.setText("Fatura IDsi");

        sendBillObjectButton.setText("Itirazi Gonder");
        sendBillObjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBillObjectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(billIdTextField))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(sendBillObjectButton)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sendBillObjectButton)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendBillObjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBillObjectButtonActionPerformed
        // TODO add your handling code here:
        String billIdS = this.billIdTextField.getText();
        JFrame f = null;
        int confirmation = 0;

        if (billIdS.equals("")) {
            f = new JFrame();
            JOptionPane.showMessageDialog(f,
                    "Lutfen fatura ID kismini bos birakmayiniz");
        } else if (Long.valueOf(billIdS) < 0) {
            f = new JFrame();
            JOptionPane.showMessageDialog(f,
                    "Lutfen fatura ID kismina negatif sayi girmeyiniz");
        } else {
            String query = "SELECT EXISTS(SELECT 1 FROM Bills WHERE BillID = "
                    + billIdS + " AND ID = " +  this.programUser.getId() + ");";
            
            try (Connection conn = DriverManager.getConnection(DatabaseUrl.URL);
                    Statement stat = conn.createStatement();
                    ResultSet result = stat.executeQuery(query)) {
                confirmation = result.getInt(1);
            } catch (SQLException exp) {
                f = new JFrame();
                JOptionPane.showMessageDialog(f, exp.toString());

            }
            if (confirmation == 1) {

                long billId = 0;

                billId = Long.valueOf(billIdS);

                query = "INSERT INTO BillObjects (ID, BillID)"
                        + "VALUES(" + this.programUser.getId()  
                        + ", " + billId + ");";

                try (Connection conn = DriverManager.getConnection(DatabaseUrl.URL);
                        Statement stat = conn.createStatement()) {
                    stat.execute(query);
                    this.parent.dispose();

                } catch (SQLException exp) {
                    JFrame j = new JFrame();
                    JOptionPane.showMessageDialog(j, exp.toString());

                }
            } else {
                f = new JFrame();
                JOptionPane.showMessageDialog(f,
                        "Lutfen var olan bir fatura IDsi giriniz");
            }

        }
       
    }//GEN-LAST:event_sendBillObjectButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField billIdTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable objectBillTable;
    private javax.swing.JButton sendBillObjectButton;
    // End of variables declaration//GEN-END:variables
}
