/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;


import javax.swing.*;
import java.sql.*;
import ClassesInterfaces.*;

/**
 *
 * @author Halil
 */
public class PayBillWindow extends javax.swing.JPanel {

    private String billId;
    private User programUser;
    private JFrame parent;
  

    public String getBillId() {
        return billId;
    }

    public JTable getPayBillTable() {
        return payBillTable;
    }

    public void setPayBillTable(JTable payBillTable) {
        this.payBillTable = payBillTable;
    }

    public void setBillId(String billId) {
        this.billId = billId;
    }

    /**
     * Creates new form PayBillWindow
     */
    public PayBillWindow(User programUser, JFrame parent) {
        initComponents();
        this.programUser = programUser;
        this.parent = parent;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        payBillTable = new javax.swing.JTable();
        jTextField6 = new javax.swing.JTextField();
        billIdTextField = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        payButton = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        jTextField2.setText("jTextField2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Lutfen odemek istediginiz faturanin IDsini giriniz");

        jScrollPane2.setViewportView(payBillTable);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(204, 204, 204));
        jTextField6.setText("Para banka hesabindan cekilecektir");

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(204, 204, 204));
        jTextField8.setText("Fatura ID");

        payButton.setText("Ode");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(billIdTextField))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(payButton)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(payButton)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        // TODO add your handling code here:
        String billIdS = this.billIdTextField.getText();
        JFrame f = null;
        int confirmation = 0;
        long moneyInBankAccount = 0;
        long amount = 0;

        if (billIdS.equals("")) {
            f = new JFrame();
            JOptionPane.showMessageDialog(f,
                    "Lutfen fatura ID kismini bos birakmayiniz");
        } else if (Long.valueOf(billIdS) < 0) {
            f = new JFrame();
            JOptionPane.showMessageDialog(f,
                    "Lutfen fatura ID kismina negatif sayi girmeyiniz");
        } else {
            String query = "SELECT EXISTS(SELECT 1 FROM Bills WHERE BillID = "
                    + billIdS + "), (SELECT BankBalance FROM BankAccounts\n"
                    + "WHERE ID = " + this.programUser.getId() + ");";
            
            try (Connection conn = DriverManager.getConnection(DatabaseUrl.URL);
                    Statement stat = conn.createStatement()) {
                
                try(ResultSet result = stat.executeQuery(query)){
                    confirmation = result.getInt(1);
                    
                }
                
                
                if (confirmation == 1) {
                    
                    query = "SELECT BillAmount FROM Bills\n"
                    + "WHERE BillID = " + billIdS + ";";
                try(ResultSet result = stat.executeQuery(query)){
                    amount = result.getLong(1);
                }
                     
                    query = "SELECT BankBalance FROM BankAccounts WHERE\n"
                            + "ID = " + this.programUser.getId();
                    
                    try(ResultSet result = stat.executeQuery(query)){
                        moneyInBankAccount = result.getLong(1);
                    }
                    
                    if(moneyInBankAccount >= amount){
                        query = "UPDATE BankAccounts SET BankBalance = "
                                + "(SELECT BankBalance FROM BankAccounts\n"
                                + "WHERE ID = " + this.programUser.getId() + 
                                " ) - " + amount + " WHERE ID = " +  
                                this.programUser.getId() + ";";
                        
                        stat.execute(query);
                        query = "DELETE FROM Bills WHERE BillId = " + billIdS;
                        stat.execute(query);
                        Engine.refresh();
                        this.parent.dispose();
                    }
                    
                    else{
                        JOptionPane.showMessageDialog(new JFrame(),
                                "Hesapinizdaki para faturanin miktarindan az"
                                        + " islem yapilamadi");
                    }      
                } else {
                    f = new JFrame();
                    JOptionPane.showMessageDialog(f,
                            "Lutfen var olan bir fatura IDsi giriniz");
                }

            } catch (SQLException exp) {
                f = new JFrame();
                JOptionPane.showMessageDialog(f, exp.toString());

            }
        }
    }//GEN-LAST:event_payButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField billIdTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTable payBillTable;
    private javax.swing.JButton payButton;
    // End of variables declaration//GEN-END:variables
}
