/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import javax.swing.*;
import java.sql.*;
import ClassesInterfaces.*;

/**
 *
 * @author Halil
 */
public class WayCreditCardDemands extends javax.swing.JPanel {

    private User programUser;
    private JFrame parent;

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    /**
     * Creates new form WayCreditCardDemands
     */
    public WayCreditCardDemands(User programUser, JFrame parent) {
        initComponents();
        this.programUser = programUser;
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        accept = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        demandID = new javax.swing.JTextField();
        deny = new javax.swing.JButton();

        jTextField5.setText("jTextField5");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Kredi Karti Istek IDleri, Limitleri ve sahipleri");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        accept.setText("Kabul Et");
        accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("Istek IDsi");

        deny.setText("Reddet");
        deny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(accept)
                        .addGap(31, 31, 31)
                        .addComponent(deny))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(demandID))
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(demandID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deny)
                    .addComponent(accept))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptActionPerformed
        // TODO add your handling code here:
        String demandId = this.demandID.getText();
        int confirmation = 0;

        if (demandId.equals("")) {
            JOptionPane.showMessageDialog(new JFrame(),
                    "Lutfen istek IDsi kismini bos birakmayiniz");
        } else {

            
            String query = "SELECT EXISTS(SELECT 1 FROM CreditCardDemands\n"
                    + "WHERE DemandID = " + demandId + ");";

            try (Connection conn = DriverManager.getConnection(DatabaseUrl.URL);
                    Statement stat = conn.createStatement();
                    ResultSet result = stat.executeQuery(query)) {
                confirmation = result.getInt(1);
            } catch (SQLException exp) {
                JOptionPane.showMessageDialog(new JFrame(), exp.toString());

            }
            if (confirmation == 1) {
                query = "INSERT INTO CreditCard (CreditCardID, ID, CreditCard"
                        + "Amount, RemainingAmount)\n"
                        + "VALUES(NULL,(SELECT ID FROM CreditCardDemands WHERE DemandID = " + demandId + "),\n"
                        + "(SELECT Amount FROM CreditCardDemands WHERE \n"
                        + "DemandID = " + demandId + "), (SELECT Amount FROM"
                        + " CreditCardDemands WHERE DemandID = " + demandId
                        + "));";

                try (Connection conn = DriverManager.getConnection(DatabaseUrl.URL);
                        Statement stat = conn.createStatement()) {
                    stat.execute(query);
                    query = "DELETE FROM CreditCardDemands WHERE \n"
                        + "DemandId = " + demandId;
                    stat.execute(query);
                    Engine.refresh();
                    this.parent.dispose();
                    
                } catch (SQLException exp) {
                    JOptionPane.showMessageDialog(new JFrame(), exp.toString());

                }
            }
            else{
                 JOptionPane.showMessageDialog(new JFrame(), 
                         "Lutfen var olan bir kredi karti istek ID'si girin"
                                 + "iz");
            }
        }

    }//GEN-LAST:event_acceptActionPerformed

    private void denyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denyActionPerformed
        // TODO add your handling code here:
         String demandId = this.demandID.getText();
        int confirmation = 0;

        if (demandId.equals("")) {
            JOptionPane.showMessageDialog(new JFrame(),
                    "Lutfen istek IDsi kismini bos birakmayiniz");
        } else {

            
            String query = "SELECT EXISTS(SELECT 1 FROM CreditCardDemands\n"
                    + "WHERE DemandID = " + demandId + ");";

            try (Connection conn = DriverManager.getConnection(DatabaseUrl.URL);
                    Statement stat = conn.createStatement();
                    ResultSet result = stat.executeQuery(query)) {
                confirmation = result.getInt(1);
            } catch (SQLException exp) {
                JOptionPane.showMessageDialog(new JFrame(), exp.toString());

            }
            if (confirmation == 1) {
                query = "DELETE FROM CreditCardDemands WHERE \n"
                        + "DemandId = " + demandId;

                try (Connection conn = DriverManager.getConnection(DatabaseUrl.URL);
                        Statement stat = conn.createStatement()) {
                    stat.execute(query);
                    this.parent.dispose();
                    
                } catch (SQLException exp) {
                    JOptionPane.showMessageDialog(new JFrame(), exp.toString());

                }
            }
            else{
                 JOptionPane.showMessageDialog(new JFrame(), 
                         "Lutfen var olan bir kredi karti istek ID'si girin"
                                 + "iz");
            }
        }

    }//GEN-LAST:event_denyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept;
    private javax.swing.JTextField demandID;
    private javax.swing.JButton deny;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
